services:
  - type: web
    name: oauth-token-generator-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://contis-projeto.vercel.app
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://contis-projeto.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Authorization,Accept
